version: '3'
services:
  app:
    build: .
    volumes:
      - ./:/var/www
    depends_on:
      - appbd

  appbd:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    volumes:
      - "./dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "mysqlBd"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
       - "33456:3306"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - app