version: "3"
services:
  php:
    build:
      context: ./php
    volumes:
      - ../:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    restart: always
    volumes:
      - $HOME/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "33456:3306"

  db_admin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "8081:80"
    depends_on:
      - db

  redis:
    image: redis
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/var/www
    depends_on:
      - php
